### ISSUE TITLE
Scrolling Issue

### ISSUE THREAD

**Issue by yousaf106** [acro5piano/react-native-big-calendar#335] opened 2021-02-04 08:35 UTC
Hi,
The calendar is not scrolling inside a ScrollView in android. Working perfectly on ios.

**Comment by acro5piano** [comment] 2021-02-04 10:51
Oh really. In my Android, it scrolls correctly. Which version do you use? Mine is Android 9.

**Comment by deepakmehra96** [comment] 2021-02-10 09:50
Yes same issue for me @yousaf106 

Calendar is not scrolling inside a ScrollView in android. Working perfectly on ios.

and @acro5piano  i guess you can resolve it by adding 

` <ScrollView nestedScrollEnabled={true}> `

then it will work in android too

**Comment by deepakmehra96** [comment] 2021-02-10 09:51
By the way i am using 
android 10

**Comment by acro5piano** [comment] 2021-02-10 10:50
@deepakmehra96 @yousaf106 
Thank you for your comments. 
I've added `nestedScrollEnabled` prop as @deepakmehra96 said and published `v0.7.4`. Can you check the new version is working?

https://github.com/acro5piano/react-native-big-calendar/pull/339

**Comment by deepakmehra96** [comment] 2021-02-10 13:00
Yes it is fixed now 

but there is an another issue too 
i am not able to click on dates and horizontal scroll for dates is not working properly too.

![Screenshot_20210210-182822](https://user-images.githubusercontent.com/37114746/107513226-e76bc700-6bcd-11eb-8b46-4b7c0e2dcbd2.jpg)

**Comment by acro5piano** [comment] 2021-02-10 13:54
@deepakmehra96 
Thank you for reporting. (Your app looks cool)
Can you improve it? Your PR is really welcome because recently I don't have time to work on it.

Ideally, we should implement this.

https://github.com/acro5piano/react-native-big-calendar/issues/138

**Comment by acro5piano** [comment] 2021-05-10 09:39
I've confirmed the behavior on my Android device. Maybe panResponder and scrollView are not working correctly. Weird thing is that sometimes it works but sometimes not.

**Comment by acro5piano** [comment] 2021-05-12 13:31
I've checked `v1.0.1` and this issue seems to have gone. If you have still this issue, feel free to open.

**Closed by acro5piano** 2021-05-12 13:31 UTC
Labels: bug
