### ISSUE TITLE
Use schedule mode

### ISSUE THREAD

**Issue by voulgarakis** [acro5piano/react-native-big-calendar#964] opened 2023-11-07 11:54 UTC
Hi all,

I have a table of items in my calendar.

The events are like this: 
[{"color": "#9F82CC", "end": 2023-10-08T09:30:00.000Z, "id": "20851", "installationId": "22425", "jobId": "23361", "start": 2023-10-08T09:00:00.000Z, "tagId": "GSOP_40200", "title": "222 | Editor User | Stratigou Sarafi 48, Kallithea"},...]

When I use the schedule mode I get this warning:
VirtualizedList: missing keys for items, make sure to specify a key or id property on each item or provide a custom keyExtractor

Do we need to have a special handle for the events in schedule mode?

Thanks

**Comment by acro5piano** [comment] 2023-11-07 15:34
I think that is a kind of bug. If you (or other people) create a pull request, I'm happy to merge it.

**Comment by acro5piano** [comment] 2023-11-07 16:49
@voulgarakis No, the problem is inside our library and you can't remove error on your side. Please wait until the issue is resolved in this library.

**Comment by charithAmila** [comment] 2023-11-08 05:36
This warning will go away with my [PR](https://github.com/acro5piano/react-native-big-calendar/pull/970).


https://github.com/acro5piano/react-native-big-calendar/pull/970/commits/ed88ef1b03c9867db100164035b8b3ad07857b11

**Comment by voulgarakis** [comment] 2023-11-08 08:21
Will this PR fix both the warning and the bug with the colors in agenda mode?

**Comment by charithAmila** [comment] 2023-11-08 14:08
Yes

**Comment by acro5piano** [comment] 2023-11-11 10:21
Must be fixed on v4.7.1. Thanks @charithAmila for the fix and @voulgarakis for reporting this.

**Closed by acro5piano** 2023-11-11 10:21 UTC
